name: firebase_auth_mocks
description: Fakes for Firebase Auth. Use this package with `google_sign_in_mocks` to write unit tests involving Firebase Authentication. Customized by Geovani Prodata
version: 0.15.0
repository: https://github.com/geovaniprodata/firebase_auth_mocks

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  meta: ^1.3.0
  equatable: ^2.0.0
  dart_jsonwebtoken: ^2.4.1
  uuid: ^4.1.0
  firebase_auth_platform_interface: ^7.0.0
  mock_exceptions: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.0.0
  jwt_decoder: ^2.0.1
